# Site settings
title: Gernot Riegler
email: riegler@icg.tugraz.at
description: > # this means to ignore newlines until "baseurl:"
  My private site.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:4000" # the base hostname & protocol for your site
# url: "http://griegler.github.io" # the base hostname & protocol for your site
twitter_username: gernotrie
github_username:  griegler

# Build settings
markdown: kramdown
